# Generated by Django 4.2.23 on 2025-09-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('tech', models.CharField(max_length=256)),
                ('users', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=128)),
                ('repos', models.URLField(max_length=512)),
                ('type', models.CharField(max_length=128)),
            ],
        ),
    ]
